### ISSUE TITLE
Missing NDC code in the csv file provided

### ISSUE THREAD

**Issue by abhishek-ch** [fabkury/ndc_map#1]
There are missing NDC codes if compared based on IBM Red Book or any other resource
My Source of NDC code is ndc_map 2020_06_17 (atc5 atc4 ingredients) and some of the missing NDC codes are like -

```
|00002010403|
|00002010502|
|00002010504|
|00002010602|
|00002010902|
|00002011002|
|00002011102|
|00002011104|
|00002011202|

```

Is there any particular reason ?

**Comment by fabkury** [comment]
The precomputed map on GitHub is the FDA NDC directory downloaded from
https://www.fda.gov/drugs/drug-approvals-and-databases/national-drug-code-directory.
I am aware it does not have all NDCs, but to be honest I do not know why.
You can still, though, run the ndc_map.R script for the codes not present in the precomputed map. If you are unable to do it yourself, and you can provide me the list of NDCs, I can run it for you.
